apiVersion: v1
data:
  type: Z2l0
  url: aHR0cHM6Ly9naXRodWIuY29tL2FyZ29wcm9qL2FyZ29jZC1leGFtcGxlLWFwcHM=
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: guestbook-repo
  namespace: argocd
type: Opaque